In [11]:
import re
import os
import glob
import pandas as pd

In [6]:
motion_pheno = '/data1/abide/Pheno/motion_all.csv'
other_pheno = '/data1/abide/Pheno/pheno.csv'
out_pheno = '/data1/abide/Pheno/glm_pheno.csv'

In [7]:
mot = pd.read_csv(motion_pheno)
phe = pd.read_csv(other_pheno)

In [41]:
# Make a combined file

with open(out_pheno, 'w') as outfile:
    outfile.write('sub,site,sex,diag,age,mean_fd\n')
    for index, row in mot.iterrows():
        sub_name = int(re.search('(?<=X00)[0-9]*', row[' ']).group())
        ses_name = re.search('_session_1_run1', row[' '])
        if not ses_name:
            print('nah', row[' '])
            continue
        FD = row['FD_scrubbed']
        phe_row = phe.loc[phe['SUB_ID'] == sub_name]
        sex = phe_row['SEX'].values[0]
        site = phe_row['SITE_ID'].values[0]
        diag = phe_row['DX_GROUP'].values[0]
        age = phe_row['AGE_AT_SCAN'].values[0]
        line = '{},{},{},{},{},{}\n'.format(sub_name, site, sex, diag, age, FD)
        outfile.write(line)

('nah', 'X0050142_session_1_run2 ')
('nah', 'X0050142_session_1_run3 ')
('nah', 'X0050143_session_1_run2 ')
('nah', 'X0050143_session_1_run3 ')
('nah', 'X0050144_session_1_run2 ')
('nah', 'X0050144_session_1_run3 ')
('nah', 'X0050145_session_1_run2 ')
('nah', 'X0050145_session_1_run3 ')
('nah', 'X0050146_session_1_run2 ')
('nah', 'X0050146_session_1_run3 ')
('nah', 'X0050147_session_1_run2 ')
('nah', 'X0050147_session_1_run3 ')
('nah', 'X0050148_session_1_run2 ')
('nah', 'X0050148_session_1_run3 ')
('nah', 'X0050149_session_1_run2 ')
('nah', 'X0050150_session_1_run2 ')
('nah', 'X0050152_session_1_run2 ')
('nah', 'X0050152_session_1_run3 ')
('nah', 'X0050153_session_1_run2 ')
('nah', 'X0050153_session_1_run3 ')
('nah', 'X0050155_session_1_run2 ')
('nah', 'X0050156_session_1_run2 ')
('nah', 'X0050156_session_1_run3 ')
('nah', 'X0050157_session_1_run2 ')
('nah', 'X0050157_session_1_run3 ')
('nah', 'X0050158_session_1_run2 ')
('nah', 'X0050159_session_1_run2 ')
('nah', 'X0050159_session_1_run3 ')
('nah', 'X0050160_session_1_run2 ')
('nah', 'X0050160_session_1_run3 ')
('nah', 'X0050161_session_1_run2 ')
('nah', 'X0050161_session_1_run3 ')
('nah', 'X0050162_session_1_run2 ')
('nah', 'X0050162_session_1_run3 ')
('nah', 'X0050163_session_1_run2 ')
('nah', 'X0050164_session_1_run2 ')
('nah', 'X0050165_session_1_run2 ')
('nah', 'X0050166_session_1_run2 ')
('nah', 'X0050166_session_1_run3 ')
('nah', 'X0050167_session_1_run2 ')
('nah', 'X0050167_session_1_run3 ')
('nah', 'X0050168_session_1_run2 ')
('nah', 'X0050168_session_1_run3 ')
('nah', 'X0050169_session_1_run2 ')
('nah', 'X0050169_session_1_run3 ')
('nah', 'X0050170_session_1_run2 ')
('nah', 'X0050170_session_1_run3 ')
('nah', 'X0050171_session_1_run2 ')
('nah', 'X0050171_session_1_run3 ')

In [9]:
mot[' ']

0     X0051328_session_1_run1
1     X0051332_session_1_run1
2     X0051333_session_1_run1
3     X0051334_session_1_run1
4     X0051335_session_1_run1
5     X0051336_session_1_run1
6     X0051338_session_1_run1
7     X0051339_session_1_run1
8     X0051340_session_1_run1
9     X0051341_session_1_run1
10    X0051342_session_1_run1
11    X0051343_session_1_run1
12    X0051344_session_1_run1
13    X0051345_session_1_run1
14    X0051346_session_1_run1
...
969    X0051330_session_1_run1
970    X0051331_session_1_run1
971    X0051349_session_1_run1
972    X0051350_session_1_run1
973    X0051351_session_1_run1
974    X0051352_session_1_run1
975    X0051353_session_1_run1
976    X0051354_session_1_run1
977    X0051355_session_1_run1
978    X0051356_session_1_run1
979    X0051357_session_1_run1
980    X0051358_session_1_run1
981    X0051359_session_1_run1
982    X0051360_session_1_run1
983    X0051361_session_1_run1
Name:  , Length: 984, dtype: object

In [4]:
mot

,,frames_scrubbed,frames_OK,FD,FD_scrubbed
0,X0051328_session_1_run1,7,113,0.149900,0.134066
1,X0051332_session_1_run1,17,103,0.151046,0.118284
2,X0051333_session_1_run1,19,101,0.223314,0.195800
3,X0051334_session_1_run1,22,98,0.241574,0.174444
4,X0051335_session_1_run1,0,120,0.135168,0.135168
5,X0051336_session_1_run1,52,68,0.362041,0.255990
6,X0051338_session_1_run1,9,111,0.178398,0.160450
7,X0051339_session_1_run1,5,115,0.141983,0.132810
8,X0051340_session_1_run1,10,110,0.130716,0.111151
9,X0051341_session_1_run1,44,76,0.452674,0.158763
10,X0051342_session_1_run1,4,116,0.125057,0.119300
11,X0051343_session_1_run1,8,112,0.181155,0.168624
12,X0051344_session_1_run1,16,104,0.212605,0.175732
13,X0051345_session_1_run1,0,120,0.132738,0.132738
14,X0051346_session_1_run1,10,110,0.151644,0.122517
15,X0051347_session_1_run1,0,120,0.122810,0.122810
16,X0051348_session_1_run1,48,72,0.333984,0.196757
17,X0051291_session_1_run1,8,112,0.153825,0.135741
18,X0051292_session_1_run1,80,40,1.005779,0.205233
19,X0051293_session_1_run1,0,120,0.114250,0.114250
20,X0051294_session_1_run1,41,79,0.376118,0.192170
21,X0051295_session_1_run1,32,88,0.281112,0.208634
22,X0051296_session_1_run1,80,40,1.521789,0.427303
23,X0051297_session_1_run1,78,42,0.558917,0.279952
24,X0051298_session_1_run1,38,82,0.309270,0.206249
25,X0051299_session_1_run1,49,71,0.645691,0.166244
26,X0051300_session_1_run1,80,40,1.283017,0.177643
27,X0051301_session_1_run1,37,83,0.321220,0.150573
28,X0051302_session_1_run1,38,82,0.287337,0.182888
29,X0051303_session_1_run1,4,116,0.096195,0.089953
...,...,...,...,...,...
954,X0051480_session_1_run1,0,150,0.124627,0.124627
955,X0051481_session_1_run1,31,119,0.327785,0.224584
956,X0051482_session_1_run1,4,146,0.158710,0.154896
957,X0051483_session_1_run1,0,150,0.168426,0.168426
958,X0051484_session_1_run1,14,136,0.204392,0.185471
959,X0051485_session_1_run1,12,138,0.237287,0.223647
960,X0051486_session_1_run1,0,150,0.141904,0.141904
961,X0051487_session_1_run1,4,146,0.172788,0.167992
962,X0051488_session_1_run1,28,122,0.256263,0.223733
963,X0051489_session_1_run1,60,90,0.338577,0.285144
964,X0051490_session_1_run1,4,146,0.165875,0.157693
965,X0051491_session_1_run1,0,150,0.121651,0.121651
966,X0051492_session_1_run1,4,146,0.175378,0.171687
967,X0051493_session_1_run1,8,142,0.173635,0.159898
968,X0051329_session_1_run1,61,139,0.334761,0.268906
969,X0051330_session_1_run1,62,138,0.283806,0.229218
970,X0051331_session_1_run1,31,169,0.238515,0.154910
971,X0051349_session_1_run1,59,141,0.275147,0.163410
972,X0051350_session_1_run1,143,57,0.532117,0.253451
973,X0051351_session_1_run1,29,171,0.225890,0.185313
974,X0051352_session_1_run1,133,67,0.735223,0.218572
975,X0051353_session_1_run1,156,44,0.981513,0.245659
976,X0051354_session_1_run1,88,112,0.466246,0.172295
977,X0051355_session_1_run1,84,116,0.382694,0.196232
978,X0051356_session_1_run1,7,193,0.156130,0.076960
979,X0051357_session_1_run1,4,196,0.118938,0.110698
980,X0051358_session_1_run1,159,41,0.718282,0.237354
981,X0051359_session_1_run1,160,40,0.915660,0.259366
982,X0051360_session_1_run1,44,156,0.193812,0.122004
983,X0051361_session_1_run1,60,140,0.598397,0.182839

In [5]:
phe

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
0,CALTECH,51456,1,4,55.40,1,R,NaN,126,118,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
1,CALTECH,51457,1,4,22.90,1,Ambi,NaN,107,119,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
2,CALTECH,51458,1,1,39.20,1,R,NaN,93,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
3,CALTECH,51459,1,1,22.80,1,R,NaN,106,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
4,CALTECH,51460,1,1,34.60,2,Ambi,NaN,133,135,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
5,CALTECH,51461,1,4,37.70,1,R,NaN,99,111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
6,CALTECH,51462,1,1,20.20,2,R,NaN,107,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
7,CALTECH,51463,1,1,20.20,2,R,NaN,102,101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
8,CALTECH,51464,1,1,20.90,1,Ambi,NaN,101,118,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
9,CALTECH,51465,1,1,20.20,1,R,NaN,96,99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
10,CALTECH,51466,1,1,27.60,1,Ambi,NaN,106,111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
11,CALTECH,51467,1,1,23.40,1,R,NaN,93,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
12,CALTECH,51468,1,1,20.10,1,R,NaN,100,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
13,CALTECH,51469,1,4,45.10,1,R,NaN,104,109,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
14,CALTECH,51470,1,4,29.10,1,R,NaN,124,127,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
15,CALTECH,51471,1,4,22.40,2,R,NaN,125,123,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
16,CALTECH,51472,1,1,17.50,1,Ambi,NaN,125,123,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
17,CALTECH,51473,1,1,21.20,1,R,NaN,-9999,-9999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
18,CALTECH,51474,1,1,20.90,1,R,NaN,100,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
19,CALTECH,51475,2,0,44.20,1,R,NaN,104,113,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
20,CALTECH,51476,2,0,39.30,1,R,NaN,123,127,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
21,CALTECH,51477,2,0,42.50,1,R,NaN,97,85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
22,CALTECH,51478,2,0,19.70,1,R,NaN,116,117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
23,CALTECH,51479,2,0,20.00,2,R,NaN,111,110,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
24,CALTECH,51480,2,0,20.80,2,R,NaN,112,109,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
25,CALTECH,51481,2,0,27.90,1,R,NaN,117,133,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
26,CALTECH,51482,2,0,21.10,2,R,NaN,103,108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
27,CALTECH,51483,2,0,20.90,1,Ambi,NaN,124,127,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
28,CALTECH,51484,2,0,23.60,1,R,NaN,128,135,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
29,CALTECH,51485,2,0,23.90,1,R,NaN,123,113,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082,YALE,50577,2,0,15.25,1,R,NaN,73,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1083,YALE,50578,2,0,12.33,1,L,NaN,104,106,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1084,YALE,50601,1,3,14.33,1,L,NaN,102,115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1085,YALE,50602,1,2,10.00,1,R,NaN,108,106,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1086,YALE,50603,1,1,13.25,1,L,NaN,76,69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1087,YALE,50604,1,1,14.42,2,R,NaN,85,79,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1088,YALE,50605,1,1,16.00,1,R,NaN,121,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1089,YALE,50606,1,3,16.42,1,R,NaN,41,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1090,YALE,50607,1,2,17.17,1,R,NaN,141,143,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1091,YALE,50608,1,3,16.58,1,R,NaN,100,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1092,YALE,50609,1,2,8.92,1,R,NaN,114,117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1093,YALE,50610,1,2,13.00,1,R,NaN,95,107,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1094,YALE,50611,1,3,11.92,1,R,NaN,86,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1095,YALE,50612,1,2,11.83,1,R,NaN,121,126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1096,YALE,50613,1,2,12.50,1,L,NaN,131,141,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1097,YALE,50614,1,1,17.75,1,R,NaN,72,57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1098,YALE,50615,1,2,8.58,2,R,NaN,119,101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1099,YALE,50616,1,3,11.83,1,R,NaN,93,106,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1100,YALE,50617,1,3,7.25,1,R,NaN,84,82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1101,YALE,50618,1,1,12.75,1,L,NaN,76,79,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1102,YALE,50619,1,1,16.50,2,R,NaN,88,86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1103,YALE,50620,1,3,12.75,2,R,NaN,114,110,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1104,YALE,50621,1,2,16.58,2,R,NaN,83,111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1105,YALE,50622,1,3,9.92,1,R,NaN,89,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1106,YALE,50623,1,3,13.66,2,R,NaN,94,101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1107,YALE,50624,1,3,11.08,2,R,NaN,90,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1108,YALE,50625,1,3,7.00,1,L,NaN,99,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1109,YALE,50626,1,3,11.08,1,L,NaN,61,66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1110,YALE,50627,1,3,9.50,2,R,NaN,88,103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1111,YALE,50628,1,3,14.42,1,R,NaN,77,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN

In [42]:
glm = pd.read_csv(out_pheno)
glm

       sub     site  sex  diag    age   mean_fd
0    51328  MAX_MUN    1     1  22.00  0.134066
1    51332  MAX_MUN    1     2  23.00  0.118284
2    51333  MAX_MUN    1     2  24.00  0.195800
3    51334  MAX_MUN    1     2  27.00  0.174444
4    51335  MAX_MUN    1     2  23.00  0.135168
5    51336  MAX_MUN    1     2  26.00  0.255990
6    51338  MAX_MUN    1     2  30.00  0.160450
7    51339  MAX_MUN    1     2  29.00  0.132810
8    51340  MAX_MUN    1     2  29.00  0.111151
9    51341  MAX_MUN    1     2  29.00  0.158763
10   51342  MAX_MUN    1     2  23.00  0.119300
11   51343  MAX_MUN    1     2  30.00  0.168624
12   51344  MAX_MUN    1     2  22.00  0.175732
13   51345  MAX_MUN    1     2  35.00  0.132738
14   51346  MAX_MUN    1     2  25.00  0.122517
15   51347  MAX_MUN    1     2  24.00  0.122810
16   51348  MAX_MUN    1     1   8.00  0.196757
17   51291   UCLA_2    1     1  16.47  0.135741
18   51292   UCLA_2    1     1  12.24  0.205233
19   51293   UCLA_2    1     1  13.08  0.114250
20   51294   UCLA_2    1     1  11.70  0.192170
21   51295   UCLA_2    1     1  10.04  0.208634
22   51296   UCLA_2    1     1  11.16  0.427303
23   51297   UCLA_2    1     1  14.27  0.279952
24   51298   UCLA_2    1     1  10.57  0.206249
25   51299   UCLA_2    1     1  14.77  0.166244
26   51300   UCLA_2    1     1  14.08  0.177643
27   51301   UCLA_2    1     1  13.28  0.150573
28   51302   UCLA_2    1     1  10.85  0.182888
29   51303   UCLA_2    2     2  13.00  0.089953
..     ...      ...  ...   ...    ...       ...
905  51480  CALTECH    2     2  20.80  0.124627
906  51481  CALTECH    1     2  27.90  0.224584
907  51482  CALTECH    2     2  21.10  0.154896
908  51483  CALTECH    1     2  20.90  0.168426
909  51484  CALTECH    1     2  23.60  0.185471
910  51485  CALTECH    1     2  23.90  0.223647
911  51486  CALTECH    1     2  22.00  0.141904
912  51487  CALTECH    1     2  17.00  0.167992
913  51488  CALTECH    1     2  23.30  0.223733
914  51489  CALTECH    1     2  34.10  0.285144
915  51490  CALTECH    1     2  44.10  0.157693
916  51491  CALTECH    1     2  56.20  0.121651
917  51492  CALTECH    1     2  18.70  0.171687
918  51493  CALTECH    2     2  29.20  0.159898
919  51329  MAX_MUN    1     1  18.00  0.268906
920  51330  MAX_MUN    1     1  45.00  0.229218
921  51331  MAX_MUN    1     1  35.00  0.154910
922  51349  MAX_MUN    1     1  11.00  0.163410
923  51350  MAX_MUN    1     1  11.00  0.253451
924  51351  MAX_MUN    1     1  11.00  0.185313
925  51352  MAX_MUN    1     1   9.00  0.218572
926  51353  MAX_MUN    1     1   7.00  0.245659
927  51354  MAX_MUN    1     1  12.00  0.172295
928  51355  MAX_MUN    1     1  11.00  0.196232
929  51356  MAX_MUN    1     2  10.00  0.076960
930  51357  MAX_MUN    1     2  11.00  0.110698
931  51358  MAX_MUN    1     2  10.00  0.237354
932  51359  MAX_MUN    1     2  13.00  0.259366
933  51360  MAX_MUN    1     2   7.00  0.122004
934  51361  MAX_MUN    1     2  16.00  0.182839

[935 rows x 6 columns]